function write_SIGEPS(jobname,outpath,DLZ,SIG,varargin)
% Schreibe Spannungen und Dehnungen in Datei
% Wenn nur Spannungen geschrieben werden dann schreibe *.pth Datei
% sonst schreibe *.sig
%
% INPUT:
% jobname   - (str) Name der Outputdatei = jobname_SIGEPS.dat
% outpath   - (str) Pfad zu OutputFolder
% DLZ       - Durchlaufzaehler
% SIG       - Verlauf der Spannungen (ESZ) e R^(3,numdata) oder (3D) e R^(6,numdata)
% varargin  - EPS Verlauf der Dehnungen (ESZ) e R^(4,numdata) oder (3D) e R^(6,numdata)
% 
% OUTPUT:
%  erzeugte Datei jobname_SIGEPS.sig
%
%__________________________________________________________________________

% ... abfangen variablen input
ntens = size(SIG,1);                                                       % Anzahl Tensorkomponenten
ndata = size(SIG,2);
if nargin == 4 % Schreibe *.pth
    dateiname = [jobname,'.pth'];                                          % Dateiname
    DATA = [DLZ;SIG];                                                      % Output Zusannemfuegen 
else % Schreibe *.sig
    dateiname = [jobname,'.sig'];                                          % Dateiname
    EPS = varargin{1,1}*100;                                               % Dehnungen in Prozent
    DATA = [DLZ;SIG;EPS];                                                  % Output Zusannemfuegen
end

% ... Dateiname
name = [outpath,'\',dateiname];                                            % Voller name

% ... oeffne Datei
fid = fopen(name,'w');

% ... Schreibe Header (je nach Spannungszustand)
% DLZ        : 21 char = 0(Vorzeichen) + 4 + 1(DezimalPunkt) + 16(Dezimalstellen)
% Jeder Wert : 15 char = 1(Vorzeichen) + 5 + 1(DezimalPunkt) + 8(Dezimalstellen)
if ntens == 6 && nargin == 5
    header = ['         DLZ         ',...
              '       S11      ',...
              '       S22      ',...
              '       S33      ',...
              '       S12      ',...
              '       S23      ',...
              '       S13      ',...
              '       E11[%%]   ',...
              '       E22[%%]   ',...
              '       E33[%%]   ',...
              '       G12[%%]   ',...
              '       G23[%%]   ',...
              '       G13[%%]   \n'];
    formspec = '%21.16f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f\n';
elseif ntens == 6 && nargin == 4
    header = ['         DLZ         ',...
              '       S11      ',...
              '       S22      ',...
              '       S33      ',...
              '       S12      ',...
              '       S23      ',...
              '       S13      \n'];
    formspec = '%21.16f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f\n';

elseif ntens == 3 && nargin == 5
    header = ['         DLZ         ',...
              '      S11      ',...
              '      S22      ',...
              '      S12      ',...
              '       E11[%%]   ',...
              '       E22[%%]   ',...
              '       E33[%%]   ',...
              '       G12[%%]   \n'];
    formspec = '%21.16f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f;%15.8f\n';
elseif ntens == 3 && nargin == 4
    header = ['         DLZ         ',...
              '       S11      ',...
              '       S22      ',...
              '       S12      \n'];
    formspec = '%21.16f;%15.8f;%15.8f;%15.8f\n';
end 

% ... Schreibe Header
fprintf(fid,'%i;%i\n',ndata,size(DATA,1));
fprintf(fid,header);

% ... Schreibe Daten in Datei
fprintf(fid,formspec,DATA);

% ... Schließe Datei
fclose(fid);
end % Ende Funktion