function [G, P] = modneuberableitung(SIG,EPS,...
                                  REFSIG,REFEPS,...
                                  EEPS,REFEEPS,dEEPS)
% =====================================================================
% G
G = [EPS(1) - REFEPS(1) , EPS(2) - REFEPS(2) ,       0            ; ...
                    0   ,                 0  ,       0            ; ...
                    0   ,                 0  , EPS(3) - REFEPS(3)];

% =====================================================================
% P
P = [SIG(1) - REFSIG(1)    ,    SIG(2) - REFSIG(2)   ,       0            ; ...
    EEPS(2) - REFEEPS(2)   , -(EEPS(1) - REFEEPS(1)) ,       0            ; ...
                    0      ,                    0    , SIG(3) - REFSIG(3)];

end % Ende Funktion